### ISSUE TITLE
DTMF 

### ISSUE THREAD

**Issue by atulgo** [jth-1996/DTMF-and-GSM-Based-Modile-Automation#1]
I want to detect DTMF using SIM800C Modem
This is what happens :

1. Put sim 'A' in modem.

2. Connect to modem over serial using Minicom.

3. Turn on DTMF detection.('AT+DDET=1\r' cmd on Minicom)

4. Initiate a call to modem using a mobile phone.

5. Accept call on modem ( 'ATA\r' cmd on Minicom)

6. Dial the digit (1,2.... etc) from the phone (send DTMF tones to modem).

7. Nothing appears on Minicom (connected to serial port)

Atul

**Comment by jth-1996** [comment]
instead of *"AT+DDET"* give *"AT+DDET=1"* as the command to turn on DTMF
detection. See if you get *"+OK"* as a response to your command from the
board. This is a more specific way to turn on DTMF detection. This Should
Work.
Regards

Jithin T

(+91-9447127836)

**Comment by atulgo** [comment]
thanks for the reply Jithin.
I had already done as u say. Should have been more clear in my query ....
Looks like the issue is with my operater.
Regards
